/*
Copyright 2020 Brandon Kalinowski
Boilerplate is Copyright 2019 Wrangler Sample Controller Authors (Apache 2.0)
*/

// Code generated by wrangler. DO NOT EDIT.

package replicator

const (
	// Package-wide consts from generator "zz_generated_register".
	GroupName = "replicator.kite.run"
)
