/*
Copyright 2020 Brandon Kalinowski
Boilerplate is Copyright 2019 Wrangler Sample Controller Authors (Apache 2.0)
*/

// Code generated by wrangler. DO NOT EDIT.

// +k8s:deepcopy-gen=package
// +groupName=replicator.kite.run
package v1alpha1
